matrix:
  include:
#  - language: node_js
#    node_js:
#    - node
#    before_script:
#    - cd frontend
#    - yarn
#    script:
#    - yarn prettier-check && yarn lint && yarn test

  - language: node_js
    node_js:
    - node
    before_script:
    - cd backend
    - yarn
    script:
    - yarn prettier-check && yarn lint
